[package]
name = "rawdinal"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-only"
publish = false

[workspace]
members = ["ffi"]
resolver = "3"

[lib]
crate-type = ["rlib"]

[dependencies]
jpeg-decoder = { version = "=0.3.2", default-features = false }
jxl-oxide = { version = "=0.11.4", default-features = false }

[dev-dependencies]
serde_json = "=1.0.145"
sha2 = "=0.10.9"

[[bin]]
name = "rawdinal-inspect"
path = "src/bin/inspect.rs"

[[bench]]
name = "decode"
harness = false

[profile.release]
overflow-checks = true

[lints.rust]
unsafe_code = "forbid"
