sonar.organization=paolo-santucci
sonar.projectKey=paolo-santucci_rawdinal
sonar.sourceEncoding=UTF-8
sonar.sources=src,ffi/src,benches,examples
sonar.tests=tests
sonar.test.inclusions=tests/**/*.rs
sonar.exclusions=target/**,build/**,tests/**/*.c
